# Generated by Django 5.0.6 on 2024-09-21 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userlibraryaccount_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlibraryaccount',
            old_name='inital_deposit_date',
            new_name='initial_deposit_date',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='accounts.userlibraryaccount'),
        ),
        migrations.RemoveField(
            model_name='userlibraryaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='userlibraryaccount',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
